[build]
# Use Dockerfile otimizado para Railway
builder = "dockerfile"
dockerfilePath = "Dockerfile.railway"

[deploy]
# Configurações de deploy (CMD definido no Dockerfile)
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

# Configurações de recursos (Railway limits)
[deploy.resources]
# Railway Hobby Plan limits
memory = "1GB"
cpu = "1vCPU"

# Variáveis de ambiente necessárias
[environments.production.variables]
FLASK_ENV = "production"
FLASK_DEBUG = "false"
LOG_LEVEL = "INFO"
VECTORIZER_TYPE = "hybrid"
CORS_ORIGINS = "https://alicit-saas.vercel.app,http://localhost:3000"

# Configurações específicas do Railway
RAILWAY_ENVIRONMENT = "production"
PYTHONUNBUFFERED = "1"
PYTHONDONTWRITEBYTECODE = "1"

# Configurações de timeout para Railway
GUNICORN_TIMEOUT = "120"
GUNICORN_WORKERS = "2"

# Configurações ML/Transformers
TOKENIZERS_PARALLELISM = "false"
OMP_NUM_THREADS = "2"
MKL_NUM_THREADS = "2"
TRANSFORMERS_CACHE = "/app/cache/transformers"
TORCH_HOME = "/app/cache/torch"

# ===============================================
# VARIÁVEIS SENSÍVEIS (configurar no Railway UI):
# ===============================================
# DATABASE_URL = "postgresql://..."
# SUPABASE_URL = "https://..."
# SUPABASE_SERVICE_KEY = "..."
# SUPABASE_ANON_KEY = "..."
# OPENAI_API_KEY = "sk-..."
# VOYAGE_API_KEY = "pa-..."
# SECRET_KEY = "..."
# REDIS_URL = "redis://..."
# ===============================================

[environments.staging]
# Configurações para staging (opcional)
[environments.staging.variables]
FLASK_ENV = "staging"
FLASK_DEBUG = "true"
LOG_LEVEL = "DEBUG" 